"""Django 训练后台任务 —— 直接调 cv-ultralytics 现有脚本"""
import os
import sys
import random
import shutil
import subprocess
import threading


# cv-ultralytics 路径：label-studio/cv-ultralytics/
_BASE = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
_CV_ULTRA = os.path.join(_BASE, 'cv-ultralytics')
if _CV_ULTRA not in sys.path:
    sys.path.insert(0, _CV_ULTRA)

_PROJ_ROOT = os.path.join(_CV_ULTRA, 'ultralytics', 'ultralytics')


def build_dataset(export_dir: str, dataset_name: str, task_type: str, classes: list):
    """
    把导出数据按 train/valid/test 划分 + 自动生成 data.yaml
    """
    dst = os.path.join(_CV_ULTRA, 'datasets', dataset_name, task_type)
    for phase in ['train', 'valid', 'test']:
        for sub in ['images', 'labels']:
            os.makedirs(os.path.join(dst, phase, sub), exist_ok=True)

    src_img = os.path.join(export_dir, 'images')
    src_lbl = os.path.join(export_dir, 'labels')

    # 先找到导出目录的实际 images/ labels/ 位置
    if not os.path.isdir(src_img):
        for item in os.listdir(export_dir):
            p = os.path.join(export_dir, item)
            if os.path.isdir(p) and os.path.isdir(os.path.join(p, 'images')):
                src_img = os.path.join(p, 'images')
                src_lbl = os.path.join(p, 'labels')
                break

    if not os.path.isdir(src_img) or not os.path.isdir(src_lbl):
        raise FileNotFoundError(f'导出数据不完整: images={os.path.isdir(src_img)}, labels={os.path.isdir(src_lbl)}')

    # 配对 images 和 labels
    pairs = []
    for img_file in os.listdir(src_img):
        for ext in ['.jpg', '.jpeg', '.png']:
            if img_file.lower().endswith(ext):
                base = img_file[:img_file.lower().rfind(ext)]
                lbl_file = os.path.join(src_lbl, base + '.txt')
                if os.path.exists(lbl_file):
                    pairs.append((img_file, lbl_file))
                break

    random.shuffle(pairs)
    total = len(pairs)
    train_n = int(total * 0.8)
    valid_n = int(total * 0.15)

    splits = {
        'train': pairs[:train_n],
        'valid': pairs[train_n:train_n + valid_n],
        'test': pairs[train_n + valid_n:],
    }

    for phase, data in splits.items():
        for img_file, lbl_file in data:
            shutil.copy2(os.path.join(src_img, img_file),
                         os.path.join(dst, phase, 'images', img_file))
            shutil.copy2(lbl_file,
                         os.path.join(dst, phase, 'labels', os.path.basename(lbl_file)))

    # 自动生成 data.yaml
    yaml_path = os.path.join(_PROJ_ROOT, 'cfg', 'datasets', f'{dataset_name}.yaml')
    content = f"""# Auto-generated by Training Service
train: {dst}/train/images
train_labels: {dst}/train/labels
val: {dst}/valid/images
val_labels: {dst}/valid/labels
test: {dst}/test/images
test_labels: {dst}/test/labels

nc: {len(classes)}
names:
"""
    for i, c in enumerate(classes):
        content += f"  {i}: {c}\n"

    os.makedirs(os.path.dirname(yaml_path), exist_ok=True)
    with open(yaml_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return True


def run_training(model_yaml: str, model_pt: str, data_yaml: str, **params):
    """直接调 YOLO model.train()"""
    from ultralytics import YOLO
    from datetime import datetime

    model = YOLO(os.path.join(_PROJ_ROOT, 'cfg', 'models', 'v8', f'{model_yaml}.yaml')).load(
        os.path.join(_PROJ_ROOT, 'models', f'{model_pt}.pt'))

    data_path = os.path.join(_PROJ_ROOT, 'cfg', 'datasets', f'{data_yaml}.yaml')
    model.train(
        data=data_path,
        epochs=params.get('epochs', 1000),
        batch=params.get('batch', 16),
        patience=params.get('patience', 200),
        imgsz=params.get('imgsz', 640),
        device=params.get('device', 0),
        pretrained=True,
        plots=True,
    )

    model.val()
    version = datetime.now().strftime('%Y%m%d%H%M%S')
    save_path = os.path.join(_CV_ULTRA, 'trained_models', f'model_v{version}')
    os.makedirs(save_path, exist_ok=True)
    model.save(os.path.join(save_path, 'model.pt'))
    print(f'训练完成，模型已保存至: {save_path}')
    return save_path
