# Generated by Django 5.1.12 on 2026-07-16 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0030_project_search_vector_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("obb", "OBB 旋转检测"),
                            ("detect", "目标检测"),
                            ("cls", "分类"),
                            ("seg", "分割"),
                        ],
                        default="obb",
                        max_length=20,
                    ),
                ),
                ("model_yaml", models.CharField(default="yolov8x-obb", max_length=255)),
                ("model_pt", models.CharField(default="yolov8x-obb", max_length=255)),
                ("data_yaml", models.CharField(default="", max_length=255)),
                (
                    "classes",
                    models.JSONField(help_text="类别列表，如 ['apple', 'banana']"),
                ),
                ("epochs", models.IntegerField(default=1000)),
                ("batch", models.IntegerField(default=16)),
                ("patience", models.IntegerField(default=200)),
                ("imgsz", models.IntegerField(default=640)),
                ("device", models.CharField(default="0", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_name", models.CharField(max_length=255)),
                (
                    "task_id",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=64, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("building", "Building Dataset"),
                            ("training", "Training"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("params", models.JSONField(default=dict)),
                ("result", models.JSONField(blank=True, default=dict, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
